version: "3.9"

services:
  functionlab-zookeeper:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: functionlab-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - functionlab_net

  functionlab-kafka:
    image: confluentinc/cp-kafka:7.7.0
    hostname: functionlab-kafka
    container_name: functionlab-kafka
    depends_on:
      - functionlab-zookeeper
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: functionlab-zookeeper:2181

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://functionlab-kafka:9092,EXTERNAL://localhost:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - functionlab_net

  functionlab-engine-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: functionlab-engine-worker
    command: ["python", "-m", "engine.workers.main"]
    env_file:
      - .env
    depends_on:
      - functionlab-kafka
    networks:
      - functionlab_net
    restart: unless-stopped

networks:
  functionlab_net:
    driver: bridge
